// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAczLGRckN0_E2Z9BBcAkoHpDhw_wPmj5o',
    appId: '1:975350765023:web:e5b754c41a6ef9c950a06a',
    messagingSenderId: '975350765023',
    projectId: 'solutionschllge',
    authDomain: 'solutionschllge.firebaseapp.com',
    storageBucket: 'solutionschllge.firebasestorage.app',
    measurementId: 'G-14CW6JTLRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpz_WIC1nnTTmrf-o9O1SwRrFuBss8yZM',
    appId: '1:975350765023:android:ecedf86c828c0c0350a06a',
    messagingSenderId: '975350765023',
    projectId: 'solutionschllge',
    storageBucket: 'solutionschllge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcXs50eQomKF5NexwH_JgtYpM25zVh11Q',
    appId: '1:975350765023:ios:a07d7d546165636250a06a',
    messagingSenderId: '975350765023',
    projectId: 'solutionschllge',
    storageBucket: 'solutionschllge.firebasestorage.app',
    iosBundleId: 'com.example.crisisMeshMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcXs50eQomKF5NexwH_JgtYpM25zVh11Q',
    appId: '1:975350765023:ios:a07d7d546165636250a06a',
    messagingSenderId: '975350765023',
    projectId: 'solutionschllge',
    storageBucket: 'solutionschllge.firebasestorage.app',
    iosBundleId: 'com.example.crisisMeshMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAczLGRckN0_E2Z9BBcAkoHpDhw_wPmj5o',
    appId: '1:975350765023:web:979adab08f0ab77450a06a',
    messagingSenderId: '975350765023',
    projectId: 'solutionschllge',
    authDomain: 'solutionschllge.firebaseapp.com',
    storageBucket: 'solutionschllge.firebasestorage.app',
    measurementId: 'G-QY7R8WMT84',
  );
}
